In [1]:
import pandas as pd
pd.set_option("display.max_rows", None)

In [2]:
import os
os.getcwd()

'/home/michael/think_complexity/dp'

In [3]:
df_raw = pd.read_csv("us_chr_dis.csv", low_memory=False)

In [4]:
df_raw.head()

,YearStart,YearEnd,LocationAbbr,LocationDesc,DataSource,Topic,Question,Response,DataValueUnit,DataValueType,...,TopicID,QuestionID,ResponseID,DataValueTypeID,StratificationCategoryID1,StratificationID1,StratificationCategoryID2,StratificationID2,StratificationCategoryID3,StratificationID3
0,2020,2020,US,United States,BRFSS,Health Status,Recent activity limitation among adults,NaN,Number,Age-adjusted Mean,...,HEA,HEA04,NaN,AGEADJMEAN,SEX,SEXF,NaN,NaN,NaN,NaN
1,2015,2019,AR,Arkansas,US Cancer DVT,Cancer,"Invasive cancer (all sites combined), incidence",NaN,Number,Number,...,CAN,CAN07,NaN,NMBR,SEX,SEXM,NaN,NaN,NaN,NaN
2,2015,2019,CA,California,US Cancer DVT,Cancer,"Cervical cancer mortality among all females, u...",NaN,Number,Number,...,CAN,CAN03,NaN,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2015,2019,CO,Colorado,US Cancer DVT,Cancer,"Invasive cancer (all sites combined), incidence",NaN,Number,Number,...,CAN,CAN07,NaN,NMBR,RACE,HIS,NaN,NaN,NaN,NaN
4,2015,2019,GA,Georgia,US Cancer DVT,Cancer,"Prostate cancer mortality among all males, und...",NaN,Number,Number,...,CAN,CAN05,NaN,NMBR,RACE,WHT,NaN,NaN,NaN,NaN

In [5]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 309215 entries, 0 to 309214
Data columns (total 34 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   YearStart                  309215 non-null  int64
 1   YearEnd                    309215 non-null  int64
 2   LocationAbbr               309215 non-null  str
 3   LocationDesc               309215 non-null  str
 4   DataSource                 309215 non-null  str
 5   Topic                      309215 non-null  str
 6   Question                   309215 non-null  str
 7   Response                   0 non-null       float64
 8   DataValueUnit              309215 non-null  str
 9   DataValueType              309215 non-null  str
 10  DataValue                  209196 non-null  float64
 11  DataValueAlt               209196 non-null  float64
 12  DataValueFootnoteSymbol    101716 non-null  str
 13  DataValueFootnote          101716 non-null  str
 14  LowConfidenceLimit         188885 non-null  float64
 15  HighConfidenceLimit        188890 non-null  float64
 16  StratificationCategory1    309215 non-null  str
 17  Stratification1            309215 non-null  str
 18  StratificationCategory2    0 non-null       float64
 19  Stratification2            0 non-null       float64
 20  StratificationCategory3    0 non-null       float64
 21  Stratification3            0 non-null       float64
 22  Geolocation                303452 non-null  str
 23  LocationID                 309215 non-null  int64
 24  TopicID                    309215 non-null  str
 25  QuestionID                 309215 non-null  str
 26  ResponseID                 0 non-null       float64
 27  DataValueTypeID            309215 non-null  str
 28  StratificationCategoryID1  309215 non-null  str
 29  StratificationID1          309215 non-null  str
 30  StratificationCategoryID2  0 non-null       float64
 31  StratificationID2          0 non-null       float64
 32  StratificationCategoryID3  0 non-null       float64
 33  StratificationID3          0 non-null       float64
dtypes: float64(14), int64(3), str(17)
memory usage: 80.2 MB

In [6]:
df_raw.shape

(309215, 34)

In [7]:
df = df_raw.copy()

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

df.head()

,yearstart,yearend,locationabbr,locationdesc,datasource,topic,question,response,datavalueunit,datavaluetype,...,topicid,questionid,responseid,datavaluetypeid,stratificationcategoryid1,stratificationid1,stratificationcategoryid2,stratificationid2,stratificationcategoryid3,stratificationid3
0,2020,2020,US,United States,BRFSS,Health Status,Recent activity limitation among adults,NaN,Number,Age-adjusted Mean,...,HEA,HEA04,NaN,AGEADJMEAN,SEX,SEXF,NaN,NaN,NaN,NaN
1,2015,2019,AR,Arkansas,US Cancer DVT,Cancer,"Invasive cancer (all sites combined), incidence",NaN,Number,Number,...,CAN,CAN07,NaN,NMBR,SEX,SEXM,NaN,NaN,NaN,NaN
2,2015,2019,CA,California,US Cancer DVT,Cancer,"Cervical cancer mortality among all females, u...",NaN,Number,Number,...,CAN,CAN03,NaN,NMBR,OVERALL,OVR,NaN,NaN,NaN,NaN
3,2015,2019,CO,Colorado,US Cancer DVT,Cancer,"Invasive cancer (all sites combined), incidence",NaN,Number,Number,...,CAN,CAN07,NaN,NMBR,RACE,HIS,NaN,NaN,NaN,NaN
4,2015,2019,GA,Georgia,US Cancer DVT,Cancer,"Prostate cancer mortality among all males, und...",NaN,Number,Number,...,CAN,CAN05,NaN,NMBR,RACE,WHT,NaN,NaN,NaN,NaN

In [8]:
df.columns.tolist()

['yearstart',
 'yearend',
 'locationabbr',
 'locationdesc',
 'datasource',
 'topic',
 'question',
 'response',
 'datavalueunit',
 'datavaluetype',
 'datavalue',
 'datavaluealt',
 'datavaluefootnotesymbol',
 'datavaluefootnote',
 'lowconfidencelimit',
 'highconfidencelimit',
 'stratificationcategory1',
 'stratification1',
 'stratificationcategory2',
 'stratification2',
 'stratificationcategory3',
 'stratification3',
 'geolocation',
 'locationid',
 'topicid',
 'questionid',
 'responseid',
 'datavaluetypeid',
 'stratificationcategoryid1',
 'stratificationid1',
 'stratificationcategoryid2',
 'stratificationid2',
 'stratificationcategoryid3',
 'stratificationid3']

In [9]:
[col for col in df.columns if "strat" in col]

['stratificationcategory1',
 'stratification1',
 'stratificationcategory2',
 'stratification2',
 'stratificationcategory3',
 'stratification3',
 'stratificationcategoryid1',
 'stratificationid1',
 'stratificationcategoryid2',
 'stratificationid2',
 'stratificationcategoryid3',
 'stratificationid3']

In [14]:
df["question_clean"] = (
    df["question"]
    .str.replace("\n", " ", regex=False)
    .str.strip()
    )

In [17]:
questions = df["question_clean"].unique()

for q in questions:
    print(q)

Recent activity limitation among adults
Invasive cancer (all sites combined), incidence
Cervical cancer mortality among all females, underlying cause
Prostate cancer mortality among all males, underlying cause
Breast cancer mortality among all females, underlying cause
Invasive cancer (all sites combined) mortality among all people, underlying cause
Diabetic ketoacidosis mortality among all people, underlying or contributing cause
Lung and bronchial cancer mortality among all people, underlying cause
Colon and rectum (colorectal) cancer mortality among all people, underlying cause
Short sleep duration among children aged 4 months to 14 years
Influenza vaccination among adults
Children and adolescents aged 6-13 years meeting aerobic physical activity guideline
Receipt of evidence-based preventive dental services in the past 12 months among children and adolescents aged 1-17 years
Arthritis among adults
Current asthma among adults
Taking medicine to control high blood pressure among adults with high blood pressure
Coronary heart disease mortality among all people, underlying cause
Adults with any disability
Frequent mental distress among adults
Short sleep duration among high school students
Quit attempts in the past year among adult current smokers
Binge drinking prevalence among adults
Chronic obstructive pulmonary disease mortality among adults aged 45 years and older, underlying cause
Frequent physical distress among adults
Obesity among adults
Received health care provider counseling for physical activity among adults with arthritis
Asthma mortality among all people, underlying cause
Current smoking among adults with chronic obstructive pulmonary disease
Binge drinking frequency among adults who binge drink
Depression among adults
Physical inactivity among adults with arthritis
High cholesterol among adults who have been screened
Taking medicine for high cholesterol among adults
Cerebrovascular disease (stroke) mortality among all people, underlying cause
Influenza vaccination among adults 18â€“64 who are at increased risk
Pneumococcal vaccination among adults aged 65 years and older
Lack of health insurance among adults aged 18-64 years
High blood pressure among adults
Diseases of the heart mortality among all people, underlying cause
Diabetes among adults
Gestational diabetes among women with a recent live birth
Diabetes mortality among all people, underlying or contributing cause
Food insecure in the past 12 months among households
Current cigarette smoking among adults
Life expectancy at birth
Fair or poor self-rated health status among adults
Alcohol use among high school students
Chronic obstructive pulmonary disease among adults
No leisure-time physical activity among adults
Provided care for someone with dementia or other cognitive impairment in the past month among adults
Binge drinking intensity among adults who binge drink
Routine checkup within the past year among adults
Binge drinking prevalence among high school students
Consumed vegetables less than one time daily among adults
Met aerobic physical activity guideline among high school students
Chronic liver disease mortality among all people, underlying cause
Incidence of treated end-stage kidney disease
Average mentally unhealthy days among adults
Consumed fruit less than one time daily among adults
High school completion among adults aged 18-24
Average recent physically unhealthy days among adults
Severe joint pain among adults with arthritis
Current smokeless tobacco use among high school students
Activity limitation due to arthritis among adults with arthritis
Consumed vegetables less than one time daily among high school students
Cigarette smoking during pregnancy among women with a recent live birth
Chronic obstructive pulmonary disease mortality among adults aged 45 years and older, underlying or contributing cause
Pneumococcal vaccination among adults aged 18â€“64 years who are at increased risk
Unemployment rate among people 16 years and older in the labor force
Subjective cognitive decline among adults aged 45 years and older
Work limitation due to arthritis among adults aged 18-64 years with arthritis
Living below 150% of the poverty threshold among all people
Provided care for a friend or family member in the past month among adults
2 or more chronic conditions among adults
Current tobacco use of any tobacco product among high school students
All teeth lost among adults aged 65 years and older
Visited dentist or dental clinic in the past year among adults
No teeth lost among adults aged 18-64 years
Mammography use among women aged 50-74 years
Short sleep duration among adults
Cervical cancer screening among women aged 21-65 years
Six or more teeth lost among adults aged 65 years and older
Colorectal cancer screening among adults aged 45-75 years
Postpartum checkup among women with a recent live birth
Hospitalization for chronic obstructive pulmonary disease as any diagnosis, Medicare-beneficiaries aged 65 years and older
No broadband internet subscription among households
Have taken an educational class to learn how to manage arthritis symptoms among adults with arthritis
Obesity among high school students
Current poor mental health among high school students
Hospitalization for heart failure as principal diagnosis, Medicare-beneficiaries aged 65 years and older
Consumed regular soda at least one time daily among high school students
Unable to pay mortgage, rent, or utility bills in the past 12 months among adults
Lack of social and emotional support needed among adults
Lack of reliable transportation in the past 12 months among adults
Met aerobic physical activity guideline for substantial health benefits, adults
Discussed symptoms of subjective cognitive decline with a health care professional among adults aged 45 years and older with subjective cognitive decline
Visited dentist or other oral health care provider in the past 12 months among children and adolescents aged 1-17 years
Hospitalization for chronic obstructive pulmonary disease as principal diagnosis, Medicare-beneficiaries aged 65 years and older
Current electronic vapor product use among high school students
Preventive dental care in the 12 months before pregnancy among women with a recent live birth
Health insurance coverage in the month before pregnancy among women with a recent live birth
Postpartum depressive symptoms among women with a recent live birth
Consumed fruit less than one time daily among high school students
Health insurance coverage after pregnancy among women with a recent live birth
Per capita alcohol consumption among people aged 14 years and older
Infants who were breastfed at 12 months
Proportion of the population protected by a comprehensive smoke-free policy prohibiting smoking in all indoor areas of workplaces and public places, including restaurants and bars
Infants who were exclusively breastfed through 6 months
Obesity among WIC children aged 2 to 4 years

In [ ]:
df['stratificationcategory1'].value_counts()

In [ ]:
df['stratification1'].value_counts()

In [ ]:
df['stratificationcategoryid1'].value_counts()

In [ ]:
df['stratificationid1'].value_counts()